### ISSUE TITLE
Fuzzing: huge memory usage take 2

### ISSUE THREAD

**Issue by newpavlov** [dgriffen/flif.rs#34]
Input:
```
FLIF11F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00FLIF\x00\x00L\xc5XifI\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00FLIF\x00\x00\x00\x00\x00\x00\x00
```

**Comment by dgriffen** [comment]
Looks to be due to a highly imbalanced maniac tree. Unfortunately the standard method of binary tree storage is terrible for this use case. It could be improved by just storing child indicies in the nodes and just placing newly created children at the end. The interesting side-effect of that is that certain cases will be highly cache-friendly.
